config/routes.rb
Rails.application.routes.draw do
  root 'main#index'

  post '/', to: 'main#index', as: 'process'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    require 'encryptor'

    @text = if params[:text]
      secret_key = params[:key]
      text = params[:text]

      if encrypt?
        Base64.encode64(Encryptor.encrypt(text, key: secret_key, algorithm: 'rc4'))
      else
        Encryptor.decrypt(Base64.decode64(text), key: secret_key, algorithm: 'rc4')
      end
    else
      ''
    end
  end

  private

  def encrypt?
    params[:encrypt].present?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
    <% if msg.is_a?(String) %>
        <%= content_tag :div, msg, :class => "flash_#{name}" %>
    <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : 'Pssstcard' %></title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header>
</header>
<main role="main">
  <div class="container">
    <div class="row">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
  </div>
</main>
</body>
</html>

app/views/main/index.html.erb
<h1>Pssstcard</h1>
<div class="row">
    <div class="col-md-8">
        <%= form_tag process_path, role: :form do %>
            <div class="form-group">
              <%= label_tag :key, 'SK (Secret key)' %>
              <%= text_field_tag :key, params[:key], class: 'form-control', required: true %>
            </div>
            <div class="form-group">
                <%= label_tag :text, 'T (Text)' %>
                <%= text_area_tag :text, @text, class: 'form-control', rows: 5, required: true  %>
            </div>

            <%= submit_tag 'Encrypt!', name: 'encrypt', class: 'btn btn-default' %>
            <%= submit_tag 'Decrypt!', name: 'decrypt', class: 'btn btn-default' %>
        <% end %>
    </div>
</div>